#!/usr/bin/env -S npx tsx
/**
 * Promote formulas (and the parameters they use) from a saved Answer's TML into
 * a Model's TML.
 *
 * Pure data transform, no network calls. Ported from ts-cli's
 * `ts model promote-formula` (thoughtspot-agent-skills tools/ts-cli/ts_cli/promote.py),
 * which the CLI version of this skill delegated Steps 7–10 to.
 *
 * Two entry points, selected by `mode` on the CLI input:
 *
 *   - `analyzeAnswer(answerTml)` — lists formulas, sets and parameters in the
 *     Answer, and for each formula the parameters and other Answer formulas it
 *     references. Drives the Step 4 selection dialog.
 *   - `promoteFormulas(input)` — selects formulas, pulls in dependencies and
 *     referenced parameters, applies the duplicate policy, rewrites column
 *     references to `[TABLE::col]` form, classifies MEASURE vs ATTRIBUTE, and
 *     returns the merged Model TML (as a plain object) ready for import.
 *
 * TML is handled as parsed JSON. Export with `edoc_format: "JSON"` and send the
 * merged object back with `JSON.stringify` — no YAML library needed.
 *
 * Two ways to run this, per SKILL.md:
 *
 *   A. Local shell + filesystem access:
 *        npx tsx promote_formulas.ts < input.json
 *      where input.json is `{"mode": "analyze", "answerTml": {...}}` or
 *      `{"mode": "promote", ...PromoteInput}`.
 *
 *   B. A sandboxed code-exec tool with no `process` (e.g. execute-thoughtspot-code):
 *      copy everything above the CLI wrapper into the `code` string, call the
 *      function with the in-scope data, and `return` its result.
 *
 * Differences from the Python original (all deliberate):
 *   - A reference to another formula by display name (`[Profit]`) is rewritten to
 *     that formula's id (`[formula_Profit]`). Model import rejects display-name
 *     formula references on first import.
 *   - When a promoted formula gets a different id in the Model than it had in the
 *     Answer (id collision), references to the old id are rewritten.
 *   - Overwrite keeps the existing Model formula's id and column entry (so other
 *     Model formulas that reference it, and properties like synonyms, survive) and
 *     replaces only the expression and column_type/aggregation.
 *   - `refOverrides` replaces a token before resolution, so unresolved references
 *     are fixed by re-running with a mapping instead of hand-editing the output.
 *   - Dependencies are followed transitively, and formulas in `excludeFormulas` are
 *     never pulled back in as dependencies.
 *   - A target that exports as a Worksheet, Table or View is rejected.
 *   - A parameter in `excludeParams` that the Model doesn't have is reported as an
 *     unresolved reference.
 */

// Loose TML shapes: only the fields this script reads or writes are typed. Every other
// field passes through untouched via the index signature.
export interface TmlFormula {
	id?: string;
	name: string;
	expr?: string;
	was_auto_generated?: boolean;
	[key: string]: unknown;
}

export interface TmlColumn {
	name: string;
	column_id?: string;
	formula_id?: string;
	properties?: Record<string, unknown>;
	[key: string]: unknown;
}

export interface TmlParameter {
	name: string;
	data_type?: string;
	description?: string;
	default_value?: string;
	dynamic_default_date?: string;
	list_config?: unknown;
	range_config?: unknown;
	[key: string]: unknown;
}

export interface ModelBody {
	model_tables?: { name: string; alias?: string; [key: string]: unknown }[];
	columns?: TmlColumn[];
	formulas?: TmlFormula[];
	parameters?: TmlParameter[];
	[key: string]: unknown;
}

/** `{guid, model: {...}}`, or a bare model body at the root. */
export interface ModelTml extends ModelBody {
	guid?: string;
	model?: ModelBody;
}

export interface AnswerTml {
	guid?: string;
	answer?: {
		formulas?: TmlFormula[];
		parameters?: TmlParameter[];
		cohorts?: { name: string; config?: { cohort_type?: string }; [key: string]: unknown }[];
		tables?: { name?: string; fqn?: string; [key: string]: unknown }[];
		[key: string]: unknown;
	};
	[key: string]: unknown;
}

export interface AnswerFormula {
	name: string;
	id: string;
	expr: string;
	wasAutoGenerated: boolean;
}

export interface AnalyzeResult {
	formulas: (AnswerFormula & { paramRefs: string[]; formulaDeps: string[] })[];
	sets: { name: string; type: string }[];
	parameters: TmlParameter[];
	dataSourceGuid: string | null;
	dataSourceName: string | null;
	_ranVia: string;
}

export interface PromoteInput {
	answerTml: AnswerTml;
	modelTml: ModelTml;
	modelGuid: string;
	/** Formula display names to promote. null = all (auto-generated ones only if includeAuto). */
	selectedFormulaNames: string[] | null;
	includeAuto?: boolean;
	/** Auto-include unselected Answer formulas that selected ones reference. Default true. */
	includeDeps?: boolean;
	/** Auto-include Answer parameters referenced by promoted formulas. Default true. */
	includeParams?: boolean;
	/** Parameter names NOT to promote (the user says the Model already has them). */
	excludeParams?: string[];
	/** Formula names the user skipped. Never pulled back in as dependencies. */
	excludeFormulas?: string[];
	duplicatePolicy?: 'skip' | 'overwrite';
	/** Replacement expressions keyed by formula display name (Step 4 option E). */
	exprOverrides?: Record<string, string>;
	/** Token replacements applied to every promoted expression, e.g. {"Rev": "SALES::REVENUE"}. */
	refOverrides?: Record<string, string>;
}

export interface PromoteResult {
	added: FormulaReport[];
	overwritten: FormulaReport[];
	skipped: { name: string; reason: string }[];
	depsAdded: string[];
	paramsAdded: { name: string; data_type: string }[];
	paramsOverwritten: { name: string; data_type: string }[];
	paramsSkipped: { name: string; reason: string }[];
	unresolvedRefs: { formula: string; ref: string }[];
	/** Full merged Model TML, `guid` at the root. null when nothing is left to promote. */
	mergedTml: ModelTml | null;
	_ranVia: string;
}

export interface FormulaReport {
	name: string;
	formula_id: string;
	column_type: 'MEASURE' | 'ATTRIBUTE';
	aggregation: 'SUM' | null;
	expr: string;
}

const REF_RE = /\[([^\]]+)\]/g;

// Canonical aggregate detector, verbatim from ts-cli spotql_ops.AGGREGATE_FUNCS.
// Requires "(" after the name so a column called "Sum" doesn't match.
const AGGREGATE_FUNCS =
	/\b(sum|count|count_distinct|unique\s+count|average|min|max|median|stddev|variance|sum_if|unique_count_if|cumulative_\w+|moving_\w+|group_aggregate|group_\w+|rank|rank_percentile|last_value|first_value)\s*\(/i;

export function extractRefs(expr: string): string[] {
	return [...(expr ?? '').matchAll(REF_RE)].map((m) => m[1]);
}

/** MEASURE iff the expression calls an aggregate. Aggregation is SUM by convention (ignored at query time). */
export function classifyExpr(expr: string): {
	column_type: 'MEASURE' | 'ATTRIBUTE';
	aggregation: 'SUM' | null;
} {
	const isAgg = AGGREGATE_FUNCS.test(expr ?? '');
	return isAgg
		? { column_type: 'MEASURE', aggregation: 'SUM' }
		: { column_type: 'ATTRIBUTE', aggregation: null };
}

function answerRoot(answerTml: AnswerTml): NonNullable<AnswerTml['answer']> {
	return answerTml?.answer ?? {};
}

const BARE_MODEL_KEYS = ['model_tables', 'columns', 'formulas'];

function modelRoot(modelTml: ModelTml): ModelBody {
	return modelTml?.model ?? modelTml;
}

/**
 * Only Models can take promoted formulas. Accepts a `{guid?, model: {...}}` document, or a
 * bare model body (`model_tables`/`columns`/`formulas` at the root). Anything else — a
 * worksheet, table, view, liveboard, ... — is rejected.
 */
function assertModel(modelTml: ModelTml): void {
	if (modelTml?.model) return;
	const keys = Object.keys(modelTml ?? {}).filter((k) => k !== 'guid');
	if (keys.some((k) => BARE_MODEL_KEYS.includes(k))) return;
	const kind = keys[0] ?? 'empty document';
	throw new Error(`Target TML is a ${kind}, not a model. Only Models can be promoted to.`);
}

function extractAnswerFormulas(answerTml: AnswerTml): AnswerFormula[] {
	return (answerRoot(answerTml).formulas ?? []).map((f) => ({
		name: f.name,
		id: f.id ?? '',
		expr: f.expr ?? '',
		wasAutoGenerated: f.was_auto_generated === true,
	}));
}

export function analyzeAnswer(answerTml: AnswerTml): AnalyzeResult {
	const answer = answerRoot(answerTml);
	const formulas = extractAnswerFormulas(answerTml);
	const parameters = answer.parameters ?? [];
	const paramNames = new Set(parameters.map((p) => p.name));
	const byId = new Map(formulas.map((f) => [f.id, f]));
	const byName = new Map(formulas.map((f) => [f.name, f]));
	const tables = answer.tables ?? [];

	return {
		formulas: formulas.map((f) => {
			const refs = extractRefs(f.expr);
			const deps = new Set<string>();
			for (const r of refs) {
				const dep = byId.get(r) ?? byName.get(r);
				if (dep && dep.name !== f.name) deps.add(dep.name);
			}
			return {
				...f,
				paramRefs: [...new Set(refs.filter((r) => paramNames.has(r)))],
				formulaDeps: [...deps],
			};
		}),
		sets: (answer.cohorts ?? []).map((c) => ({
			name: c.name,
			type: c.config?.cohort_type === 'ADVANCED' ? 'query set' : 'column set',
		})),
		parameters,
		dataSourceGuid: tables[0]?.fqn ?? null,
		dataSourceName: tables[0]?.name ?? null,
		_ranVia: 'promote_formulas.ts:analyzeAnswer',
	};
}

function buildModelParam(p: TmlParameter): TmlParameter {
	const entry: TmlParameter = { name: p.name, data_type: p.data_type };
	if (p.description) entry.description = p.description;
	if ('default_value' in p) entry.default_value = p.default_value;
	else if ('dynamic_default_date' in p) entry.dynamic_default_date = p.dynamic_default_date;
	if (p.list_config) entry.list_config = p.list_config;
	if (p.range_config) entry.range_config = p.range_config;
	return entry;
}

export function promoteFormulas(input: PromoteInput): PromoteResult {
	const includeDeps = input.includeDeps ?? true;
	const includeParams = input.includeParams ?? true;
	const policy = input.duplicatePolicy ?? 'skip';
	const excludeParams = new Set(input.excludeParams ?? []);
	const excludeFormulas = new Set(input.excludeFormulas ?? []);
	assertModel(input.modelTml);
	const exprOverrides = input.exprOverrides ?? {};
	const refOverrides = input.refOverrides ?? {};

	const allAnswer = extractAnswerFormulas(input.answerTml).map((f) =>
		f.name in exprOverrides ? { ...f, expr: exprOverrides[f.name] } : f,
	);
	const answerParams = answerRoot(input.answerTml).parameters ?? [];

	// --- selection ---
	let selected: AnswerFormula[];
	if (input.selectedFormulaNames && input.selectedFormulaNames.length > 0) {
		const wanted = new Set(input.selectedFormulaNames);
		selected = allAnswer.filter((f) => wanted.has(f.name));
		const missing = [...wanted].filter((n) => !selected.some((f) => f.name === n));
		if (missing.length) {
			throw new Error(`Formula(s) not found in answer: ${missing.sort().join(', ')}`);
		}
	} else {
		selected = allAnswer.filter((f) => input.includeAuto || !f.wasAutoGenerated);
	}
	selected = selected.filter((f) => !excludeFormulas.has(f.name));

	// --- formula dependencies (transitive) ---
	const depsAdded: string[] = [];
	if (includeDeps) {
		const byId = new Map(allAnswer.map((f) => [f.id, f]));
		const byName = new Map(allAnswer.map((f) => [f.name, f]));
		const queue = [...selected];
		while (queue.length) {
			const f = queue.shift()!;
			for (const r of extractRefs(f.expr)) {
				const dep = byId.get(r) ?? byName.get(r);
				if (dep && !selected.includes(dep) && !excludeFormulas.has(dep.name)) {
					selected.push(dep);
					depsAdded.push(dep.name);
					queue.push(dep);
				}
			}
		}
	}

	// --- referenced parameters ---
	const paramsSkipped: { name: string; reason: string }[] = [];
	const paramsToPromote: TmlParameter[] = [];
	if (includeParams) {
		const needed = new Map<string, TmlParameter>();
		for (const f of selected) {
			for (const r of extractRefs(f.expr)) {
				const p = answerParams.find((ap) => ap.name === r);
				if (p) needed.set(p.name, p);
			}
		}
		for (const p of needed.values()) {
			if (excludeParams.has(p.name)) paramsSkipped.push({ name: p.name, reason: 'excluded' });
			else paramsToPromote.push(p);
		}
	}

	// --- duplicates ---
	const merged = structuredClone(input.modelTml);
	const m = modelRoot(merged);
	const formulas = (m.formulas ??= []);
	const columns = (m.columns ??= []);
	const existingFormulaByName = new Map(formulas.map((f) => [f.name, f]));
	const existingParamNames = new Set((m.parameters ?? []).map((p) => p.name));

	const skipped: { name: string; reason: string }[] = [];
	const toAdd: AnswerFormula[] = [];
	const toOverwrite: AnswerFormula[] = [];
	for (const f of selected) {
		if (!existingFormulaByName.has(f.name)) toAdd.push(f);
		else if (policy === 'overwrite') toOverwrite.push(f);
		else skipped.push({ name: f.name, reason: 'duplicate' });
	}

	const paramsToAdd: TmlParameter[] = [];
	const paramsToOverwrite: TmlParameter[] = [];
	for (const p of paramsToPromote) {
		if (!existingParamNames.has(p.name)) paramsToAdd.push(p);
		else if (policy === 'overwrite') paramsToOverwrite.push(p);
		else paramsSkipped.push({ name: p.name, reason: 'already in model' });
	}

	const base = {
		skipped,
		depsAdded,
		paramsSkipped,
		_ranVia: 'promote_formulas.ts:promoteFormulas',
	};
	if (toAdd.length === 0 && toOverwrite.length === 0) {
		return {
			...base,
			added: [],
			overwritten: [],
			paramsAdded: [],
			paramsOverwritten: [],
			unresolvedRefs: [],
			mergedTml: null,
		};
	}

	// --- assign Model formula ids ---
	const usedIds = new Set<string>(formulas.flatMap((f) => (f.id ? [f.id] : [])));
	const newIdByName = new Map<string, string>();
	for (const f of toOverwrite) {
		const existing = existingFormulaByName.get(f.name)!;
		// An existing Model formula without an id gets the conventional one.
		existing.id ??= `formula_${f.name}`;
		usedIds.add(existing.id);
		newIdByName.set(f.name, existing.id);
	}
	for (const f of toAdd) {
		let id = `formula_${f.name}`;
		if (usedIds.has(id)) id = `formula_${f.name}_promoted`;
		let n = 2;
		while (usedIds.has(id)) id = `formula_${f.name}_promoted_${n++}`;
		usedIds.add(id);
		newIdByName.set(f.name, id);
	}

	// Formula-reference lookup: token -> Model formula id.
	const formulaIdByToken = new Map<string, string>();
	for (const f of formulas) {
		if (!f.id) continue;
		formulaIdByToken.set(f.id, f.id);
		formulaIdByToken.set(f.name, f.id);
	}
	for (const f of [...toAdd, ...toOverwrite]) {
		const id = newIdByName.get(f.name)!;
		if (f.id) formulaIdByToken.set(f.id, id);
		formulaIdByToken.set(f.name, id);
	}
	// A skipped duplicate resolves to the Model's existing formula.
	for (const s of skipped) {
		const answerF = selected.find((f) => f.name === s.name);
		const existing = existingFormulaByName.get(s.name)!;
		if (answerF?.id && existing.id) formulaIdByToken.set(answerF.id, existing.id);
	}

	// Only parameters that will really exist in the Model resolve. An excluded parameter
	// the Model doesn't have stays unresolved, so a wrong "the Model already has it"
	// answer surfaces here and not as "parameter not found" at import.
	const paramNames = new Set<string>([
		...(m.parameters ?? []).map((p) => p.name),
		...paramsToPromote.map((p) => p.name),
	]);
	const colIdByName = new Map<string, string>();
	for (const c of columns) if (c.column_id) colIdByName.set(c.name, c.column_id);
	const tableNames = new Set<string>();
	for (const t of m.model_tables ?? []) {
		tableNames.add(t.name);
		if (t.alias) tableNames.add(t.alias);
	}

	// --- rewrite references ---
	const unresolvedRefs: { formula: string; ref: string }[] = [];
	const rewrite = (f: AnswerFormula): string =>
		f.expr.replace(REF_RE, (whole, rawToken: string) => {
			const token = refOverrides[rawToken] ?? rawToken;
			if (token.includes('::')) {
				if (!tableNames.has(token.split('::', 1)[0])) {
					unresolvedRefs.push({ formula: f.name, ref: `[${rawToken}]` });
					return whole;
				}
				return `[${token}]`;
			}
			const fid = formulaIdByToken.get(token);
			if (fid) return `[${fid}]`;
			if (paramNames.has(token)) return `[${token}]`;
			const colId = colIdByName.get(token);
			if (colId) return `[${colId}]`;
			unresolvedRefs.push({ formula: f.name, ref: `[${rawToken}]` });
			return whole;
		});

	const report = (f: AnswerFormula, expr: string): FormulaReport => ({
		name: f.name,
		formula_id: newIdByName.get(f.name)!,
		...classifyExpr(expr),
		expr,
	});

	const overwritten: FormulaReport[] = [];
	for (const f of toOverwrite) {
		const expr = rewrite(f);
		const r = report(f, expr);
		const formula = formulas.find((x) => x.name === f.name);
		if (formula) formula.expr = expr;
		const col = columns.find((c) => c.formula_id === r.formula_id);
		if (col) {
			const properties: Record<string, unknown> = {
				...(col.properties ?? {}),
				column_type: r.column_type,
			};
			if (r.aggregation) properties.aggregation = r.aggregation;
			else delete properties.aggregation;
			col.properties = properties;
		} else {
			columns.push(columnEntry(r));
		}
		overwritten.push(r);
	}

	const added: FormulaReport[] = [];
	for (const f of toAdd) {
		const expr = rewrite(f);
		const r = report(f, expr);
		formulas.push({ id: r.formula_id, name: f.name, expr });
		columns.push(columnEntry(r));
		added.push(r);
	}

	// --- parameters ---
	if (paramsToOverwrite.length) {
		const names = new Set(paramsToOverwrite.map((p) => p.name));
		m.parameters = (m.parameters ?? []).filter((p) => !names.has(p.name));
	}
	if (paramsToAdd.length || paramsToOverwrite.length) {
		m.parameters = [
			...(m.parameters ?? []),
			...[...paramsToAdd, ...paramsToOverwrite].map(buildModelParam),
		];
	}

	// guid must sit at the document root, first key, or import creates a duplicate.
	const { guid: _drop, ...rest } = merged;
	const mergedTml: ModelTml = { guid: input.modelGuid, ...rest };

	return {
		...base,
		added,
		overwritten,
		paramsAdded: paramsToAdd.map((p) => ({ name: p.name, data_type: p.data_type ?? '' })),
		paramsOverwritten: paramsToOverwrite.map((p) => ({
			name: p.name,
			data_type: p.data_type ?? '',
		})),
		unresolvedRefs,
		mergedTml,
	};
}

function columnEntry(r: FormulaReport): TmlColumn {
	const properties: Record<string, unknown> = { column_type: r.column_type };
	if (r.aggregation) properties.aggregation = r.aggregation;
	return { name: r.name, formula_id: r.formula_id, properties };
}

// --- CLI wrapper (local `npx tsx` runs only — uses `process`, not available
// in a sandboxed code-exec tool; see the file header) ---

function readStdin(): Promise<string> {
	return new Promise((resolve, reject) => {
		let data = '';
		process.stdin.setEncoding('utf8');
		process.stdin.on('data', (chunk) => (data += chunk));
		process.stdin.on('end', () => resolve(data));
		process.stdin.on('error', reject);
	});
}

async function main(): Promise<void> {
	const input = JSON.parse(await readStdin());
	const output =
		input.mode === 'analyze' ? analyzeAnswer(input.answerTml) : promoteFormulas(input);
	process.stdout.write(JSON.stringify(output, null, 2));
}

if (typeof require !== 'undefined' && typeof module !== 'undefined' && require.main === module) {
	main().catch((err) => {
		process.stderr.write(String(err) + '\n');
		process.exit(1);
	});
}
